name: Sonar Master

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: macos-latest
    steps:
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: github
          LABEL: 'GitHub'
          ICON: 'github'
          STATUS: 'BYOBTest'
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
