# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build my app"
  lane :deploy_dev do
    get_certificates(
			development: true,
			username: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id))
    get_provisioning_profile(
  		development: true,
  		username: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id))
    gym(
  		workspace: "CI-Sample.xcworkspace",
  		scheme: "CI-Sample-Dev",
  		silent: false,
  		clean: true,
  		output_directory: "Output-ipa/",
  		output_name: "CI-Sample-Dev.ipa",
  		export_method: "development")
  end

  lane :tests do
		xcclean(workspace:  "CI-Sample.xcworkspace",
			scheme: "CI-Sample-Dev")
		run_tests(workspace: "CI-Sample.xcworkspace",
			devices: ["iPhone 8"],
			scheme: "CI-Sample-Dev")
	end
end
