name: Build & Test

on:
  schedule:
    - cron:  '0 0 * * SUN'    # Every sunday

  workflow_dispatch:

jobs:
  Test:
    runs-on: macos-latest
    steps:
      # Sets Xcode version to 11.7
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7'
      - uses: actions/checkout@v2
      # Runs unit tests
      - name: Build for test
        run: xcodebuild -workspace CI-Sample.xcworkspace -scheme CI-Sample-Dev test -destination "platform=iOS Simulator,name=iPhone 11" -derivedDataPath ./Build -enableCodeCoverage YES
      # Reports job status as a slack notification
      - name: Report Status
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,commit,author,ref,workflow,job
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
