name: Sonar Master

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e5b206f59c78440f11df3cceeefd05fe
          filename: shields.json
          label: Hello
          message: World
          color: orange
