name: Sonar Main

on:
  schedule:
    - cron:  '0 0 * * SUN'    # Every sunday

  workflow_dispatch:

jobs:
  Sonar_Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Get coverage from Sonar
        run: |
          threshold=80
          median=40
          color=success
          totalCoverage=$(curl -X GET -u ${{ secrets.SONAR_USERNAME }}:${{ secrets.SONAR_PASSWORD }} https://ciq-quality.mpsa.com/api/measures/component\?componentId\=${{ secrets.SONAR_COMPONENT_ID_MASTER }}\&metricKeys\=coverage | python3 -c "import sys, json; print(int(json.load(sys.stdin)['component']['measures'][0]['value']))")
          echo "::set-output name=COVERAGE::${totalCoverage}%"
          echo "master branch coverage : ${totalCoverage}"
          if [ $totalCoverage -ge ${threshold} ]
          then
          color=success
          elif [ $totalCoverage -ge ${median} ]
          then
          color=yellow
          else
          color=red
          fi
          echo "::set-output name=COVERAGE_COLOR::${color}"
        id: coverage
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e5b206f59c78440f11df3cceeefd05fe
          filename: shields.json
          label: Build Coverage
          message: ${{ steps.coverage.outputs.COVERAGE }}
          color: ${{ steps.coverage.outputs.COVERAGE_COLOR }}
