name: Sonar Master

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Sonar_Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Get coverage from Sonar
        run: |
          totalCoverage=$(curl -X GET -u ${{ secrets.SONAR_USERNAME }}:${{ secrets.SONAR_PASSWORD }} https://ciq-quality.mpsa.com/api/measures/component\?componentId\=${{ secrets.SONAR_COMPONENT_ID_MASTER }}\&metricKeys\=coverage | python3 -c "import sys, json; print(json.load(sys.stdin)['component']['measures'][0]['value'])")
          echo "::set-output name=COVERAGE::${totalCoverage}%"
          echo "master branch coverage : ${totalCoverage}"
        id: coverage
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e5b206f59c78440f11df3cceeefd05fe
          filename: shields.json
          label: Build Coverage
          message: ${{ steps.coverage.outputs.COVERAGE }}
          color: green
